### ISSUE TITLE
Towers do not always aim at correct target.

### ISSUE THREAD

**Issue by MarkuBu** [mjaun/android-anuto#199]
I noticed, that towers do not always aim at the correct target. 

For example: a Flash Tower should aim the last enemy, but sometimes. I made a screenshot for an example.

![photo1641468731](https://user-images.githubusercontent.com/16163058/148376909-4274b81c-1fb9-49a5-b3ac-f4235a2c3641.jpeg)

I marked the tower with a red circle. This tower should aim the last enemy, but in this case it aims somewhere in the middle.

I also often noticed, that towers don't aim the first target.

**Comment by mjaun** [comment]
Did you maybe activate the option "lock target"? In that case a tower will continue to aim at the same target until it is either dead or out of range. Only then a new target is picked according to the chosen strategy.

**Comment by MarkuBu** [comment]
D'OH!

My fault, sorry.
