### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by easyaspi314** [mjaun/android-anuto#201]
Apparently the changes in #200 are now causing crashes in the F-Droid build shortly after launch, which did not show up in testing.

**Comment by mjaun** [comment]
The issue should be fixed with [a1542ee](https://github.com/mjaun/android-anuto/commit/a1542ee97d4c2cdde191c9dc2a908127c33c4239). I also improved the simulator a bit to detect the issue.

**Comment by easyaspi314** [comment]
Wow. How did I not notice that one... 😣

**Comment by mjaun** [comment]
No issues :slightly_smiling_face:
