### ISSUE TITLE
What does the pink circle mean?

### ISSUE THREAD

**Issue by DamienCassou** [mjaun/android-anuto#217]
After some time, enemies start to have a pink circle (like a heart) in the middle. I haven't found any information about the meaning of this. Can someone please explain?

**Comment by cyphase** [comment]
It means that enemy has been teleported back to the beginning. Enemies can only be teleported once, so it's a way for you to know which enemies won't be able to be teleported again.

The teleporter is the third tier of the 500-credit turret.

**Comment by DamienCassou** [comment]
Thank you for your quick answer. I have updated the wiki accordingly:

- the [change in the Enemies page](https://github.com/mjaun/android-anuto/wiki/Enemies/_compare/b8d015fda5ae89fca2b512968f4220a9e62edb2f...dbef7fcdaa27e2ba94d8bea9026fe7abb5a30412)
- the [change in the Towers page](https://github.com/mjaun/android-anuto/wiki/Towers/_compare/7f972096aa89f4d114e3b9d13a9426c2355099dd...4dbe2c717bdad10128bb4c5864d25d13bf2612a0)
